#!/usr/bin/env bash

USAGE="Usage: launch_instance.sh -n <name> -o <outdir> -t <type> -a <AMI id> -s <security group> -b <disk size> -e <ip allocation id> -k <key name>\n
\n
-n  user-specified instance name.\n
-o  output directory. Will be created if doesn't exist.
-t  AWS instance type e.g. t2.micro.\n
-a  AMI id in the format ami-xxxxxx.\n
-s  Security group id in the format sg-xxxxxx.\n
-b  Block size of additional disk. In gigabytes.\n
-e  Elastic ip allocation id in the format eipalloc-xxxxxxx.\n
-k  Key name. Should be available for AWS.\n
-h  This helper.\n"

while getopts ":n:o:t:a:s:b:e:k:h" opt
do
  case $opt in
    n)
      NAME=$OPTARG
      ;;
    o)
      OUTDIR=$OPTARG
      ;;
    t)
      TYPE=$OPTARG
      ;;
    a)
      AMI=$OPTARG
      ;;
    s)
      SECGROUP=$OPTARG
      ;;
    b)
      BLOCK=$OPTARG
      ;;
    e)
      ALLOCID=$OPTARG
      ;;
    k)
      KEY=$OPTARG
      ;;
    h)
      echo -e $USAGE  >&2
      exit 1
      ;;
    \?)
      echo -e "Invalid option: -$OPTARG \n" >&2
      echo -e $USAGE >&2
      exit 1
      ;;
    :)
      echo -e "Option -$OPTARG requires an argument. \n"
      echo -e $USAGE >&2
      exit 1
      ;;
  esac
done

# print usage if no options are passed
if [ $OPTIND -eq 1 ]
then
  echo -e "No options were passed. \n" >&2
  echo -e $USAGE >&2
  exit 1
fi

# required options
if [ "$NAME" == "" ]; then echo "option -n is missing, but required">&2 && exit 1; fi
if [ "$TYPE" == "" ]; then echo "option -t is missing, but required">&2 && exit 1; fi
if [ "$AMI" == "" ]; then echo "option -a is missing, but required">&2 && exit 1; fi
if [ "$SECGROUP" == "" ]; then echo "option -s is missing, but required">&2 && exit 1; fi
if [ "$BLOCK" == "" ]; then echo "option -b is missing, but required">&2 && exit 1; fi
if [ "$ALLOCID" == "" ]; then echo "option -e is missing, but required">&2 && exit 1; fi
if [ "$KEY" == "" ]; then echo "option -k is missing, but required">&2 && exit 1; fi

# if output dir not given, use current
if [ "$OUTDIR" == "" ]
then
  OUTDIR="."
fi

mkdir -p $OUTDIR/log

# start running instance
echo "creating instance with type $TYPE from $AMI" >&2

aws ec2 run-instances \
--image-id $AMI \
--count 1 \
--instance-type $TYPE \
--key-name $KEY \
--security-group-ids $SECGROUP \
--block-device-mappings "[{\"DeviceName\":\"/dev/sdf\",\"Ebs\":{\"VolumeSize\":$BLOCK,\"DeleteOnTermination\":true}}]" \
> $OUTDIR/log/$NAME.startup.json

# get instance ID
INSTANCE=`cat $OUTDIR/log/$NAME.startup.json | python3 -c "import sys, json; print(json.load(sys.stdin)['Instances'][0]['InstanceId'])"`

echo "waiting for instance to start .. " >&2
sleep 5

STATE=0
# state binary should be 16 if it's running
while [ $STATE -ne 16 ]
do
  sleep 10
  echo "checking state .. " >&2
  aws ec2 describe-instance-status --instance-ids $INSTANCE > $OUTDIR/log/$NAME.state.json

  # check for emtpy IntstanceStatuses:
  grep "\"InstanceStatuses\"\: \[\]" $OUTDIR/log/$NAME.state.json >/dev/null

  if [ $? != 0 ]
  then
    echo "instance is running" >&2

    # get state binary:
    STATE=`cat $OUTDIR/log/$NAME.state.json \
    | python3 -c "import sys, json; print(json.load(sys.stdin)['InstanceStatuses'][0]['InstanceState']['Code'])"`
  else
    # instance is not running if InstanceStatuses is empty
    echo "instance not running, retrying .." >&2
  fi
done

# associate elastic IP
echo "Associating elastic IP .. " >&2

aws ec2 associate-address --allocation-id $ALLOCID --instance-id $INSTANCE > $OUTDIR/log/$NAME.association.json

# name the instance
echo "Setting name to $NAME" >&2

aws ec2 create-tags --resources $INSTANCE --tags Key=Name,Value=$NAME

# get instance IP
aws ec2 describe-instances --instance-ids $INSTANCE > $OUTDIR/log/$NAME.description.json

IP=`cat $OUTDIR/log/$NAME.description.json \
| python3 -c "import sys, json; print(json.load(sys.stdin)['Reservations'][0]['Instances'][0]['PublicIpAddress'])"`

echo "Instance can be appoached at $IP with $KEY" >&2
